#1. Database Creation
CREATE DATABASE retail_db;
USE retail_db;


#2.Data validation
SHOW TABLES;
SELECT* FROM business_analytics_dataset_10000_rows;
SELECT COUNT(*) AS total_rows FROM business_analytics_dataset_10000_rows;

#3.Data cleaning
SELECT 
SUM(Order_ID IS NULL) AS OrderID_nulls,
SUM(Customer_ID IS NULL) AS CustomerID_nulls,
SUM(Order_Date IS NULL) AS OrderDate_nulls,
SUM(Region IS NULL) AS Region_nulls,
SUM(Product_Category IS NULL) AS Category_nulls,
SUM(Customer_Segment IS NULL) AS Segment_nulls,
SUM(Quantity IS NULL) AS Quantity_nulls,
SUM(Unit_Price IS NULL) AS UnitPrice_nulls,
SUM(Discount_Rate IS NULL) AS Discount_nulls,
SUM(Revenue IS NULL) AS Revenue_nulls,
SUM(Cost IS NULL) AS Cost_nulls,
SUM(Profit IS NULL) AS Profit_nulls,
SUM(Payment_Method IS NULL) AS Payment_nulls
FROM business_analytics_dataset_10000_rows;


SELECT Order_ID, COUNT(*) 
FROM business_analytics_dataset_10000_rows
GROUP BY Order_ID
HAVING COUNT(*) > 1;



SELECT *
FROM business_analytics_dataset_10000_rows
WHERE Order_ID IN (
    SELECT Order_ID
    FROM business_analytics_dataset_10000_rows
    GROUP BY Order_ID
    HAVING COUNT(*) > 1
);

#4. Exploratory Data Analysis
#What is the total revenue generated by the business?
SELECT SUM(Revenue) AS total_revenue
FROM business_analytics_dataset_10000_rows;

#What is the total profit generated from all sales?
SELECT SUM(Profit) AS total_profit
FROM business_analytics_dataset_10000_rows;


#What percentage of revenue is converted into profit?
SELECT 
ROUND((SUM(Profit)/SUM(Revenue))*100,2) AS profit_margin
FROM business_analytics_dataset_10000_rows;



#How many unique customers purchased from the business?
SELECT COUNT(DISTINCT Customer_ID)
FROM business_analytics_dataset_10000_rows;


#What is the average revenue generated per order?
SELECT 
ROUND(SUM(Revenue)/COUNT(DISTINCT Order_ID),2) AS avg_order_value
FROM business_analytics_dataset_10000_rows;


# Which segment makes most revenue?
SELECT 
    Customer_Segment,
    COUNT(DISTINCT Customer_ID) AS total_customers,
    SUM(Revenue) AS total_revenue,
    SUM(Profit) AS total_profit
FROM business_analytics_dataset_10000_rows
GROUP BY Customer_Segment
ORDER BY total_revenue DESC;

#what is the average revenue per customer
SELECT 
    Customer_Segment,
    ROUND(SUM(Revenue) / COUNT(DISTINCT Customer_ID), 2) AS avg_revenue_per_customer
FROM business_analytics_dataset_10000_rows
GROUP BY Customer_Segment;


#What is the total revenue by region
SELECT 
    Region,
    SUM(Revenue) AS total_revenue,
    SUM(Profit) AS total_profit
FROM business_analytics_dataset_10000_rows
GROUP BY Region
ORDER BY total_revenue DESC;


#What is the total sales by region and product category
SELECT 
    Region,
    Product_Category,
    SUM(Revenue) AS total_revenue
FROM business_analytics_dataset_10000_rows
GROUP BY Region, Product_Category
ORDER BY Region, total_revenue DESC;


#Which product category generates the highest sales revenue?
SELECT Product_Category, SUM(Revenue) AS total_revenue
FROM business_analytics_dataset_10000_rows
GROUP BY Product_Category;



#Which region has the highest profit margin?
SELECT 
    Region,
    ROUND((SUM(Profit) / SUM(Revenue)) * 100, 2) AS profit_margin_percentage
FROM business_analytics_dataset_10000_rows
GROUP BY Region
ORDER BY profit_margin_percentage DESC;

#What is the overall financial performance of the business?
SELECT 
    SUM(Revenue) AS total_revenue,
    SUM(Cost) AS total_cost,
    SUM(Profit) AS total_profit
FROM business_analytics_dataset_10000_rows;

#How does the company’s revenue change month by month over time?
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS month,
    SUM(Revenue) AS monthly_revenue
FROM business_analytics_dataset_10000_rows
GROUP BY month
ORDER BY month;



#.How does the company’s revenue change month by month over time?
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS month,
    ROUND(SUM(Profit),2) AS monthly_profit
FROM business_analytics_dataset_10000_rows
GROUP BY month
ORDER BY month;




